"""Constants for the BMW CarData integration."""

DOMAIN = "cardata"
DEFAULT_SCOPE = "authenticate_user openid cardata:api:read cardata:streaming:read"
DEVICE_CODE_URL = "https://customer.bmwgroup.com/gcdm/oauth/device/code"
TOKEN_URL = "https://customer.bmwgroup.com/gcdm/oauth/token"
API_BASE_URL = "https://api-cardata.bmwgroup.com"
API_VERSION = "v1"
DEFAULT_STREAM_HOST = "customer.streaming-cardata.bmwgroup.com"
DEFAULT_STREAM_PORT = 9000
DEFAULT_REFRESH_INTERVAL = 45 * 60  # seconds
MQTT_KEEPALIVE = 15
DEBUG_LOG = True
DIAGNOSTIC_LOG_INTERVAL = 60

HV_BATTERY_CONTAINER_NAME = "BimmerData HV Battery"
HV_BATTERY_CONTAINER_PURPOSE = "High voltage battery telemetry"
HV_BATTERY_DESCRIPTORS = [
    "vehicle.drivetrain.batteryManagement.batterySizeMax",
    "vehicle.drivetrain.electricEngine.hvsMaxEnergyAbsolute",
    "vehicle.drivetrain.batteryManagement.maxEnergy",
    "vehicle.drivetrain.batteryManagement.header",
    "vehicle.drivetrain.electricEngine.charging.acRestriction.factor",
    "vehicle.drivetrain.electricEngine.charging.authentication.status",
    "vehicle.drivetrain.electricEngine.charging.chargingMode",
    "vehicle.drivetrain.electricEngine.charging.connectorStatus",
    "vehicle.drivetrain.electricEngine.charging.connectionType",
    "vehicle.drivetrain.electricEngine.charging.consumptionOverLifeTime.engineOff.gridEnergy",
    "vehicle.drivetrain.electricEngine.charging.consumptionOverLifeTime.engineOff.referenceDistance",
    "vehicle.drivetrain.electricEngine.charging.consumptionOverLifeTime.engineOn.gridEnergy",
    "vehicle.drivetrain.electricEngine.charging.consumptionOverLifeTime.engineOn.referenceDistance",
    "vehicle.drivetrain.electricEngine.charging.consumptionOverLifeTime.overall.gridEnergy",
    "vehicle.drivetrain.electricEngine.charging.consumptionOverLifeTime.overall.referenceDistance",
    "vehicle.drivetrain.electricEngine.charging.hvStatus",
    "vehicle.drivetrain.electricEngine.charging.isImmediateChargingSystemReason",
    "vehicle.drivetrain.electricEngine.charging.isSingleImmediateCharging",
    "vehicle.drivetrain.electricEngine.charging.lastChargingReason",
    "vehicle.drivetrain.electricEngine.charging.lastChargingResult",
    "vehicle.drivetrain.electricEngine.charging.method",
    "vehicle.drivetrain.electricEngine.charging.phaseNumber",
    "vehicle.drivetrain.electricEngine.charging.reasonChargingEnd",
    "vehicle.drivetrain.electricEngine.charging.profile.climatizationActive",
    "vehicle.drivetrain.electricEngine.charging.profile.isRcpConfigComplete",
    "vehicle.drivetrain.electricEngine.charging.profile.settings.biDirectionalCharging.dischargeAllowed",
    "vehicle.drivetrain.electricEngine.charging.profile.timerType",
    "vehicle.drivetrain.electricEngine.charging.routeOptimizedChargingStatus",
    "vehicle.drivetrain.electricEngine.charging.smeEnergyDeltaFullyCharged",
    "vehicle.drivetrain.electricEngine.charging.status",
    "vehicle.drivetrain.electricEngine.charging.timeRemaining",
    "vehicle.drivetrain.electricEngine.charging.timeToFullyCharged",
    "vehicle.drivetrain.electricEngine.kombiRemainingElectricRange",
    "vehicle.drivetrain.totalRemainingRange",
    "vehicle.trip.segment.end.drivetrain.batteryManagement.hvSoc",
    "vehicle.body.chargingPort.combinedStatus",
    "vehicle.body.chargingPort.dcStatus",
    "vehicle.body.chargingPort.isoSessionId",
    "vehicle.body.chargingPort.isHospitalityActive",
    "vehicle.body.chargingPort.lockedStatus",
    "vehicle.body.chargingPort.plugEventId",
    "vehicle.body.chargingPort.status",
    "vehicle.body.chargingPort.statusClearText",
    "vehicle.powertrain.electric.battery.biDirectionalCharging.availability",
    "vehicle.powertrain.electric.battery.charging.acLimit.isActive",
    "vehicle.powertrain.electric.battery.charging.acLimit.max",
    "vehicle.powertrain.electric.battery.charging.acLimit.min",
    "vehicle.powertrain.electric.battery.charging.acLimit.selected",
    "vehicle.powertrain.electric.battery.charging.acousticLimit",
    "vehicle.powertrain.electric.battery.charging.authenticationStatus",
    "vehicle.powertrain.electric.battery.charging.batteryCarePersisted.isActive",
    "vehicle.powertrain.electric.battery.charging.batteryCarePersisted.isPreservingChargingMode",
    "vehicle.powertrain.electric.battery.charging.batteryCarePersisted.isReducedTargetSoe",
    "vehicle.powertrain.electric.battery.charging.cableCheckVoltage",
    "vehicle.powertrain.electric.battery.charging.dcChargingModeActive",
    "vehicle.powertrain.electric.battery.charging.history.sessionsList",
    "vehicle.powertrain.electric.battery.charging.power",
    "vehicle.powertrain.electric.battery.charging.settingsList",
    "vehicle.powertrain.electric.battery.charging.timeRemaining",
    "vehicle.powertrain.electric.battery.stateOfCharge.target",
    "vehicle.powertrain.electric.battery.stateOfCharge.targetMin",
    "vehicle.powertrain.electric.battery.stateOfCharge.targetSoCForProfessionalMode",
    "vehicle.powertrain.electric.battery.stateOfHealth.displayed",
    "vehicle.powertrain.electric.range.target",
    "vehicle.powertrain.tractionBattery.charging.port.anyPosition.flap.isAutomaticOpenAndCloseActive",
    "vehicle.powertrain.tractionBattery.charging.port.anyPosition.flap.isOpen",
    "vehicle.powertrain.tractionBattery.charging.port.anyPosition.isPlugged",
    "vehicle.powertrain.tractionBattery.charging.port.frontLeft.flap.isAutomaticOpenAndCloseActive",
    "vehicle.powertrain.tractionBattery.charging.port.frontLeft.flap.isOpen",
    "vehicle.powertrain.tractionBattery.charging.port.frontLeft.isPlugged",
    "vehicle.powertrain.tractionBattery.charging.port.frontMiddle.flap.isAutomaticOpenAndCloseActive",
    "vehicle.powertrain.tractionBattery.charging.port.frontMiddle.flap.isOpen",
    "vehicle.powertrain.tractionBattery.charging.port.frontMiddle.isPlugged",
    "vehicle.powertrain.tractionBattery.charging.port.frontRight.flap.isAutomaticOpenAndCloseActive",
    "vehicle.powertrain.tractionBattery.charging.port.frontRight.flap.isOpen",
    "vehicle.powertrain.tractionBattery.charging.port.frontRight.isPlugged",
    "vehicle.powertrain.tractionBattery.charging.port.rearLeft.flap.isAutomaticOpenAndCloseActive",
    "vehicle.powertrain.tractionBattery.charging.port.rearLeft.flap.isOpen",
    "vehicle.powertrain.tractionBattery.charging.port.rearLeft.isPlugged",
    "vehicle.powertrain.tractionBattery.charging.port.rearMiddle.flap.isAutomaticOpenAndCloseActive",
    "vehicle.powertrain.tractionBattery.charging.port.rearMiddle.flap.isOpen",
    "vehicle.powertrain.tractionBattery.charging.port.rearMiddle.isPlugged",
    "vehicle.powertrain.tractionBattery.charging.port.rearRight.flap.isAutomaticOpenAndCloseActive",
    "vehicle.powertrain.tractionBattery.charging.port.rearRight.flap.isOpen",
    "vehicle.powertrain.tractionBattery.charging.port.rearRight.isPlugged",
]
