"""Descriptor title overrides generated from BMW catalogue."""

DESCRIPTOR_TITLES = {
    "vehicle.vehicle.antiTheftAlarmSystem.alarm.activationTime": "Alarm activation time",
    "vehicle.vehicle.antiTheftAlarmSystem.alarm.armStatus": "Alarm arming state",
    "vehicle.vehicle.antiTheftAlarmSystem.alarm.isOn": "Alarm active",
    "vehicle.electricalSystem.battery.serviceDemand.recharge": "Battery recharge required",
    "vehicle.electricalSystem.battery.serviceDemand.replace": "Battery health state",
    "vehicle.electricalSystem.battery.stateOfCharge": "Battery charge level (12V)",
    "vehicle.electricalSystem.battery.stateOfChargePlausibility": "Battery charge level plausibility (12V)",
    "vehicle.electricalSystem.battery.voltage": "Battery voltage (12V)",
    "vehicle.electricalSystem.battery48V.stateOfHealth.displayed": "Battery health state (48V)",
    "vehicle.powertrain.electric.battery.biDirectionalCharging.availability": "Battery EV Bidirectional charging capability",
    "vehicle.powertrain.electric.battery.charging.acLimit.isActive": "Battery EV Charging limit state",
    "vehicle.powertrain.electric.battery.charging.acLimit.max": "Battery EV Maximum charging current",
    "vehicle.powertrain.electric.battery.charging.acLimit.min": "Battery EV Minimum charging current",
    "vehicle.powertrain.electric.battery.charging.acLimit.selected": "Battery EV Charging current limit",
    "vehicle.powertrain.electric.battery.charging.acousticLimit": "Battery EV Acoustic charging limit",
    "vehicle.powertrain.electric.battery.charging.batteryCarePersisted.isActive": "Battery EV Battery care mode active",
    "vehicle.powertrain.electric.battery.charging.batteryCarePersisted.isPreservingChargingMode": "Battery EV Battery care charge mode",
    "vehicle.powertrain.electric.battery.charging.batteryCarePersisted.isReducedTargetSoe": "Battery EV Reduced target state of energy",
    "vehicle.powertrain.electric.battery.charging.cableCheckVoltage": "Battery EV Cable check voltage",
    "vehicle.powertrain.electric.battery.charging.dcChargingModeActive": "Battery EV DC charging mode",
    "vehicle.powertrain.electric.battery.charging.history.sessionsList": "Battery EV Charging history",
    "vehicle.powertrain.electric.battery.charging.power": "Battery EV Charging power",
    "vehicle.powertrain.electric.battery.charging.preferenceSmartCharging": "Battery EV Smart charging option",
    "vehicle.powertrain.electric.battery.charging.settingsList": "Battery EV Location-based charging settings",
    "vehicle.powertrain.electric.battery.preconditioning.automaticMode.statusFeedback": "Battery EV Automatic preconditioning state",
    "vehicle.powertrain.electric.battery.preconditioning.manualMode.statusFeedback": "Battery EV Manual preconditioning state",
    "vehicle.powertrain.electric.battery.preconditioning.state": "Battery EV Preconditioning state",
    "vehicle.powertrain.electric.battery.stateOfCharge.target": "Battery EV Target state of charge",
    "vehicle.powertrain.electric.battery.stateOfCharge.targetMin": "Battery EV Target state of charge (min)",
    "vehicle.powertrain.electric.battery.stateOfCharge.targetSoCForProfessionalMode": "Battery EV Target state of charge (professional mode)",
    "vehicle.powertrain.electric.battery.stateOfHealth.displayed": "Battery EV Battery health state (SOCE)",
    "vehicle.drivetrain.batteryManagement.batterySizeMax": "Battery HV Max size",
    "vehicle.drivetrain.batteryManagement.header": "Battery HV State Of Charge",
    "vehicle.drivetrain.batteryManagement.maxEnergy": "Battery HV Energy content",
    "vehicle.drivetrain.electricEngine.charging.acAmpere": "Charging EV AC charging current",
    "vehicle.drivetrain.electricEngine.charging.acRestriction.factor": "Charging EV AC restriction factor",
    "vehicle.drivetrain.electricEngine.charging.acRestriction.isChosen": "Charging EV AC restriction selection",
    "vehicle.drivetrain.electricEngine.charging.acVoltage": "Charging EV AC charging voltage",
    "vehicle.drivetrain.electricEngine.charging.authentication.status": "Charging EV Authentication state",
    "vehicle.drivetrain.electricEngine.charging.chargingMode": "Charging EV Charging mode",
    "vehicle.drivetrain.electricEngine.charging.connectionType": "Charging EV Charging connection type",
    "vehicle.drivetrain.electricEngine.charging.connectorStatus": "Charging EV Connector state",
    "vehicle.drivetrain.electricEngine.charging.consumptionOverLifeTime.engineOff.gridEnergy": "Charging EV Energy supplied (engine off)",
    "vehicle.drivetrain.electricEngine.charging.consumptionOverLifeTime.engineOff.referenceDistance": "Charging EV Reference distance (engine off)",
    "vehicle.drivetrain.electricEngine.charging.consumptionOverLifeTime.engineOn.gridEnergy": "Charging EV Energy supplied (engine on)",
    "vehicle.drivetrain.electricEngine.charging.consumptionOverLifeTime.engineOn.referenceDistance": "Charging EV Reference distance (engine on)",
    "vehicle.drivetrain.electricEngine.charging.consumptionOverLifeTime.overall.gridEnergy": "Charging EV Energy supplied total",
    "vehicle.drivetrain.electricEngine.charging.consumptionOverLifeTime.overall.referenceDistance": "Charging EV Reference distance total",
    "vehicle.drivetrain.electricEngine.charging.hvpmFinishReason": "Charging EV Charging end reason",
    "vehicle.drivetrain.electricEngine.charging.hvStatus": "Charging EV HV system state",
    "vehicle.drivetrain.electricEngine.charging.isImmediateChargingSystemReason": "Charging EV Immediate charging reason",
    "vehicle.drivetrain.electricEngine.charging.isSingleImmediateCharging": "Charging EV Instant charging state",
    "vehicle.drivetrain.electricEngine.charging.lastChargingReason": "Charging EV Last charging reason",
    "vehicle.drivetrain.electricEngine.charging.lastChargingResult": "Charging EV Last charging result",
    "vehicle.drivetrain.electricEngine.charging.level": "Charging EV Predicted State Of Charge",
    "vehicle.drivetrain.electricEngine.charging.method": "Charging EV Charging method",
    "vehicle.drivetrain.electricEngine.charging.modeDeviation": "Charging EV Charging mode deviation",
    "vehicle.drivetrain.electricEngine.charging.phaseNumber": "Charging EV Charging phases",
    "vehicle.drivetrain.electricEngine.charging.profile.climatizationActive": "Charging EV Climatization active",
    "vehicle.drivetrain.electricEngine.charging.profile.isRcpConfigComplete": "Charging EV RCP config complete",
    "vehicle.drivetrain.electricEngine.charging.profile.mode": "Charging EV Charging profile",
    "vehicle.drivetrain.electricEngine.charging.profile.preference": "Charging EV Charging preference",
    "vehicle.drivetrain.electricEngine.charging.profile.settings.biDirectionalCharging.departureTimeRelevant": "Charging EV Departure time relevant",
    "vehicle.drivetrain.electricEngine.charging.profile.settings.biDirectionalCharging.dischargeAllowed": "Charging EV Discharge allowed",
    "vehicle.drivetrain.electricEngine.charging.profile.timerType": "Charging EV Timer type",
    "vehicle.drivetrain.electricEngine.charging.reasonChargingEnd": "Charging EV Charging end cause",
    "vehicle.drivetrain.electricEngine.charging.routeOptimizedChargingStatus": "Charging EV Route optimized charging state",
    "vehicle.drivetrain.electricEngine.charging.smeEnergyDeltaFullyCharged": "Charging EV Energy to full charge",
    "vehicle.drivetrain.electricEngine.charging.status": "Charging EV Charging state",
    "vehicle.drivetrain.electricEngine.charging.timeRemaining": "Charging EV Remaining time estimate",
    "vehicle.drivetrain.electricEngine.charging.timeToFullyCharged": "Charging EV Time to full charge",
    "vehicle.drivetrain.electricEngine.charging.windowSelection": "Charging EV Window selection",
    "vehicle.powertrain.electric.chargingDuration.displayControl": "Charging EV Charging time display",
    "vehicle.powertrain.electric.departureTime.displayControl": "Charging EV Departure time display",
    "vehicle.body.chargingPort.combinedStatus": "Charging Port connection state",
    "vehicle.body.chargingPort.dcStatus": "Charging Port plug (DC) state",
    "vehicle.body.chargingPort.isHospitalityActive": "Charging Port plug post-charge lock state",
    "vehicle.body.chargingPort.isoSessionId": "Charging Port session ID",
    "vehicle.body.chargingPort.lockedStatus": "Charging Port plug lock state",
    "vehicle.body.chargingPort.plugEventId": "Charging Port plug event ID",
    "vehicle.body.chargingPort.status": "Charging Port plug state",
    "vehicle.body.chargingPort.statusClearText": "Charging Port state text",
    "vehicle.body.flap.isLocked": "Charging Port flap lock",
    "vehicle.body.flap.isPermanentlyUnlocked": "Charging Port flap permanent lock state",
    "vehicle.powertrain.tractionBattery.charging.port.anyPosition.flap.isAutomaticOpenAndCloseActive": "Charging Port flap automatic open/close (any position)",
    "vehicle.powertrain.tractionBattery.charging.port.anyPosition.flap.isOpen": "Charging Port flap state (any position)",
    "vehicle.powertrain.tractionBattery.charging.port.anyPosition.isPlugged": "Charging Port plugged (any position)",
    "vehicle.powertrain.tractionBattery.charging.port.frontLeft.flap.isAutomaticOpenAndCloseActive": "Charging Port flap automatic open/close (front left)",
    "vehicle.powertrain.tractionBattery.charging.port.frontLeft.flap.isOpen": "Charging Port flap state (front left)",
    "vehicle.powertrain.tractionBattery.charging.port.frontLeft.isPlugged": "Charging Port plugged (front left)",
    "vehicle.powertrain.tractionBattery.charging.port.frontMiddle.flap.isAutomaticOpenAndCloseActive": "Charging Port flap automatic open/close (front middle)",
    "vehicle.powertrain.tractionBattery.charging.port.frontMiddle.flap.isOpen": "Charging Port flap state (front middle)",
    "vehicle.powertrain.tractionBattery.charging.port.frontMiddle.isPlugged": "Charging Port plugged (front middle)",
    "vehicle.powertrain.tractionBattery.charging.port.frontRight.flap.isAutomaticOpenAndCloseActive": "Charging Port flap automatic open/close (front right)",
    "vehicle.powertrain.tractionBattery.charging.port.frontRight.flap.isOpen": "Charging Port flap state (front right)",
    "vehicle.powertrain.tractionBattery.charging.port.frontRight.isPlugged": "Charging Port plugged (front right)",
    "vehicle.powertrain.tractionBattery.charging.port.rearLeft.flap.isAutomaticOpenAndCloseActive": "Charging Port flap automatic open/close (rear left)",
    "vehicle.powertrain.tractionBattery.charging.port.rearLeft.flap.isOpen": "Charging Port flap state (rear left)",
    "vehicle.powertrain.tractionBattery.charging.port.rearLeft.isPlugged": "Charging Port plugged (rear left)",
    "vehicle.powertrain.tractionBattery.charging.port.rearMiddle.flap.isAutomaticOpenAndCloseActive": "Charging Port flap automatic open/close (rear middle)",
    "vehicle.powertrain.tractionBattery.charging.port.rearMiddle.flap.isOpen": "Charging Port flap state (rear middle)",
    "vehicle.powertrain.tractionBattery.charging.port.rearMiddle.isPlugged": "Charging Port plugged (rear middle)",
    "vehicle.powertrain.tractionBattery.charging.port.rearRight.flap.isAutomaticOpenAndCloseActive": "Charging Port flap automatic open/close (rear right)",
    "vehicle.powertrain.tractionBattery.charging.port.rearRight.flap.isOpen": "Charging Port flap state (rear right)",
    "vehicle.powertrain.tractionBattery.charging.port.rearRight.isPlugged": "Charging Port plugged (rear right)",
    "vehicle.cabin.climate.timers.overwriteTimer.action": "Climate Timer Next-Only state",
    "vehicle.cabin.climate.timers.overwriteTimer.hour": "Climate Timer Next-Only (hour)",
    "vehicle.cabin.climate.timers.overwriteTimer.minute": "Climate Timer Next-Only (minute)",
    "vehicle.cabin.climate.timers.weekdaysTimer1.action": "Climate Timer Weekly 1 state",
    "vehicle.cabin.climate.timers.weekdaysTimer1.hour": "Climate Timer Weekly 1 (hour)",
    "vehicle.cabin.climate.timers.weekdaysTimer1.minute": "Climate Timer Weekly 1 (minute)",
    "vehicle.cabin.climate.timers.weekdaysTimer2.action": "Climate Timer Weekly 2 state",
    "vehicle.cabin.climate.timers.weekdaysTimer2.hour": "Climate Timer Weekly 2 (hour)",
    "vehicle.cabin.climate.timers.weekdaysTimer2.minute": "Climate Timer Weekly 2 (minute)",
    "vehicle.cabin.convertible.roofRetractableStatus": "Convertible roof retractable state",
    "vehicle.cabin.convertible.roofStatus": "Convertible roof overall state",
    "vehicle.cabin.door.row1.driver.isOpen": "Door state (front driver)",
    "vehicle.cabin.door.row1.driver.position": "Door position (front driver)",
    "vehicle.cabin.door.row1.passenger.isOpen": "Door state (front passenger)",
    "vehicle.cabin.door.row1.passenger.position": "Door position (front passenger)",
    "vehicle.cabin.door.row2.driver.isOpen": "Door state (rear driver)",
    "vehicle.cabin.door.row2.driver.position": "Door position (rear driver)",
    "vehicle.cabin.door.row2.passenger.isOpen": "Door state (rear passenger)",
    "vehicle.cabin.door.row2.passenger.position": "Door position (rear passenger)",
    "vehicle.cabin.door.lock.status": "Doors lock",
    "vehicle.cabin.door.status": "Doors overall state",
    "vehicle.cabin.infotainment.navigation.currentLocation.altitude": "GPS altitude",
    "vehicle.cabin.infotainment.navigation.currentLocation.fixStatus": "GPS navigation fix state",
    "vehicle.cabin.infotainment.navigation.currentLocation.heading": "GPS heading",
    "vehicle.cabin.infotainment.navigation.currentLocation.latitude": "GPS latitude",
    "vehicle.cabin.infotainment.navigation.currentLocation.longitude": "GPS longitude",
    "vehicle.cabin.infotainment.navigation.currentLocation.numberOfSatellites": "GPS satellite count",
    "vehicle.cabin.infotainment.navigation.destinationSet.arrivalTime": "GPS arrival time",
    "vehicle.cabin.infotainment.navigation.destinationSet.distance": "GPS distance to destination",
    "vehicle.cabin.infotainment.navigation.destinationSet.latitude": "GPS destination latitude",
    "vehicle.cabin.infotainment.navigation.destinationSet.longitude": "GPS destination longitude",
    "vehicle.cabin.infotainment.navigation.pointsOfInterests.available": "GPS available poi spaces",
    "vehicle.cabin.infotainment.navigation.pointsOfInterests.max": "GPS max poi spaces",
    "vehicle.cabin.infotainment.navigation.remainingRange": "GPS remaining range",
    "vehicle.learningNavigation": "GPS Learning navigation data",
    "vehicle.body.hood.isOpen": "Hood state",
    "vehicle.privacySettings.dataCollection.regulations.obfcm": "Legal OBFCM data transfer consent",
    "vehicle.vehicleIdentification.connectedDriveContractList": "Legal Connected drive contracts",
    "vehicle.drivetrain.fuelSystem.consumptionOverLifeTime.inChargeIncreasing.referenceDistance": "OBFCM Reference distance (charging mode)",
    "vehicle.drivetrain.fuelSystem.consumptionOverLifeTime.overall.fuel": "OBFCM Fuel consumption total",
    "vehicle.drivetrain.fuelSystem.consumptionOverLifeTime.overall.referenceDistance": "OBFCM Reference distance total",
    "vehicle.drivetrain.fuelSystem.consumptionOverLifeTime.inChargeDepleting.fuel": "OBFCM PHEV Fuel consumption (engine off)",
    "vehicle.drivetrain.fuelSystem.consumptionOverLifeTime.inChargeDepleting.referenceDistanceEngineOff": "OBFCM PHEV Reference distance (engine off)",
    "vehicle.drivetrain.fuelSystem.consumptionOverLifeTime.inChargeDepleting.referenceDistanceEngineOn": "OBFCM PHEV Reference distance (engine on)",
    "vehicle.drivetrain.fuelSystem.consumptionOverLifeTime.inChargeIncreasing.fuel": "OBFCM PHEV Fuel consumption (charging mode)",
    "vehicle.cabin.hvac.preconditioning.configuration.isRemoteEngineStartDisclaimer": "Preconditioning Remote engine start disclaimer",
    "vehicle.vehicle.preConditioning.activity": "Preconditioning state",
    "vehicle.vehicle.preConditioning.error": "Preconditioning error reason",
    "vehicle.vehicle.preConditioning.isRemoteEngineRunning": "Preconditioning engine used",
    "vehicle.vehicle.preConditioning.isRemoteEngineStartAllowed": "Preconditioning engine use allowed",
    "vehicle.vehicle.preConditioning.remainingTime": "Preconditioning remaining  time",
    "vehicle.cabin.hvac.preconditioning.status.comfortState": "Preconditioning  comfort state",
    "vehicle.cabin.hvac.preconditioning.status.isExteriorMirrorHeatingActive": "Preconditioning  exterior mirror heating active",
    "vehicle.cabin.hvac.preconditioning.status.progress": "Preconditioning  progress",
    "vehicle.cabin.hvac.preconditioning.status.rearDefrostActive": "Preconditioning  rear defrost active",
    "vehicle.cabin.hvac.preconditioning.status.remainingRunningTime": "Preconditioning  remaining running time",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row1.driverSide.cooling": "Preconditioning Default Seat cooling (front driver)",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row1.driverSide.heating": "Preconditioning Default Seat heating (front driver)",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row1.passengerSide.cooling": "Preconditioning Default Seat cooling (front passenger)",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row1.passengerSide.heating": "Preconditioning Default Seat heating (front passenger)",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row2.driverSide.cooling": "Preconditioning Default Seat cooling (rear driver)",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row2.driverSide.heating": "Preconditioning Default Seat heating (rear driver)",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row2.passengerSide.cooling": "Preconditioning Default Seat cooling (rear passenger)",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row2.passengerSide.heating": "Preconditioning Default Seat heating (rear passenger)",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row3.driverSide.cooling": "Preconditioning Default Seat cooling (third row driver)",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row3.driverSide.heating": "Preconditioning Default Seat heating (third row driver)",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row3.passengerSide.cooling": "Preconditioning Default Seat cooling (third row passenger)",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row3.passengerSide.heating": "Preconditioning Default Seat heating (third row passenger)",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.steeringWheel.heating": "Preconditioning Default Steering wheel heating",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.targetTemperature": "Preconditioning Default Target temperature",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row1.driverSide.cooling": "Preconditioning Direct Seat cooling (front driver)",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row1.driverSide.heating": "Preconditioning Direct Seat heating (front driver)",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row1.passengerSide.cooling": "Preconditioning Direct Seat cooling (front passenger)",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row1.passengerSide.heating": "Preconditioning Direct Seat heating (front passenger)",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row2.driverSide.cooling": "Preconditioning Direct Seat cooling (rear driver)",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row2.driverSide.heating": "Preconditioning Direct Seat heating (rear driver)",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row2.passengerSide.cooling": "Preconditioning Direct Seat cooling (rear passenger)",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row2.passengerSide.heating": "Preconditioning Direct Seat heating (rear passenger)",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row3.driverSide.cooling": "Preconditioning Direct Seat cooling (third row driver)",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row3.driverSide.heating": "Preconditioning Direct Seat heating (third row driver)",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row3.passengerSide.cooling": "Preconditioning Direct Seat cooling (third row passenger)",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row3.passengerSide.heating": "Preconditioning Direct Seat heating (third row passenger)",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.steeringWheel.heating": "Preconditioning Direct Steering wheel heating",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.targetTemperature": "Preconditioning Direct Target temperature",
    "vehicle.cabin.hvac.statusAirPurification": "Purification Air purification state",
    "vehicle.drivetrain.fuelSystem.level": "Range Tank level (%)",
    "vehicle.drivetrain.fuelSystem.remainingFuel": "Range Tank level",
    "vehicle.drivetrain.lastRemainingRange": "Range Total range (last sent)",
    "vehicle.drivetrain.totalRemainingRange": "Range Estimate during charging",
    "vehicle.drivetrain.avgElectricRangeConsumption": "Range EV Average electric consumption",
    "vehicle.drivetrain.electricEngine.hvsMaxEnergyAbsolute": "Range EV Battery energy max",
    "vehicle.drivetrain.electricEngine.kombiRemainingElectricRange": "Range EV Remaining range",
    "vehicle.drivetrain.electricEngine.remainingElectricRange": "Range EV Estimate during charging",
    "vehicle.powertrain.electric.range.displayControl": "Range EV Display control",
    "vehicle.powertrain.electric.range.target": "Range EV Remaining (set target based)",
    "vehicle.cabin.seat.row1.driverSide.cooling": "Seat Cooling (front driver)",
    "vehicle.cabin.seat.row1.driverSide.heating": "Seat Heating (front driver)",
    "vehicle.cabin.seat.row1.passengerSide.cooling": "Seat Cooling (front passenger)",
    "vehicle.cabin.seat.row1.passengerSide.heating": "Seat Heating (front passenger)",
    "vehicle.cabin.seat.row2.driverSide.cooling": "Seat Cooling (rear driver)",
    "vehicle.cabin.seat.row2.driverSide.heating": "Seat Heating (rear driver)",
    "vehicle.cabin.seat.row2.passengerSide.cooling": "Seat Cooling (rear passenger)",
    "vehicle.cabin.seat.row2.passengerSide.heating": "Seat Heating (rear passenger)",
    "vehicle.cabin.seat.row3.driverSide.cooling": "Seat Cooling (third row driver)",
    "vehicle.cabin.seat.row3.driverSide.heating": "Seat Heating (third row driver)",
    "vehicle.cabin.seat.row3.passengerSide.cooling": "Seat Cooling (third row passenger)",
    "vehicle.cabin.seat.row3.passengerSide.heating": "Seat Heating (third row passenger)",
    "vehicle.serviceDemand.defect.id": "Service Live diagnostics",
    "vehicle.sevice.preferredSevicePartner": "Service Preferred service partner",
    "vehicle.status.checkControlMessages": "Service Check control messages",
    "vehicle.status.conditionBasedServices": "Service Condition based services",
    "vehicle.status.conditionBasedServicesAverageDistancePerDay": "Service CBS average distance per day",
    "vehicle.status.conditionBasedServicesCount": "Service CBS report count",
    "vehicle.status.serviceDistance.next": "Service Distance to next service",
    "vehicle.status.serviceDistance.yellow": "Service Next service distance threshold",
    "vehicle.status.serviceTime.hUandAuServiceYellow": "Service Inspection time threshold",
    "vehicle.status.serviceTime.inspectionDateLegal": "Service Next inspection date",
    "vehicle.status.serviceTime.yellow": "Service Next service time threshold",
    "vehicle.vehicle.avgSpeed": "Speed average",
    "vehicle.vehicle.speedRange.lowerBound": "Speed lower range",
    "vehicle.vehicle.speedRange.upperBound": "Speed upper range",
    "vehicle.cabin.steeringWheel.heating": "Steering Wheel heating",
    "vehicle.cabin.sunroof.overallStatus": "Sunroof overall state",
    "vehicle.cabin.sunroof.relativePosition": "Sunroof relative position",
    "vehicle.cabin.sunroof.shade.position": "Sunroof Sunshade position",
    "vehicle.cabin.sunroof.status": "Sunroof state",
    "vehicle.cabin.sunroof.tiltStatus": "Sunroof tilt state",
    "vehicle.channel.teleservice.lastAutomaticServiceCallTime": "Teleservice Automatic service call time",
    "vehicle.channel.teleservice.lastBreakdownCallTime": "Teleservice Breakdown call time",
    "vehicle.channel.teleservice.lastManualCallTime": "Teleservice Manual service call time",
    "vehicle.channel.teleservice.lastTeleserviceReportTime": "Teleservice report time",
    "vehicle.channel.teleservice.status": "Teleservice availability state",
    "vehicle.chassis.axle.row1.wheel.left.tire.pressure": "Tire pressure (front left)",
    "vehicle.chassis.axle.row1.wheel.left.tire.pressureTarget": "Tire pressure target (front left)",
    "vehicle.chassis.axle.row1.wheel.left.tire.temperature": "Tire temperature (front left)",
    "vehicle.chassis.axle.row1.wheel.right.tire.pressure": "Tire pressure (front right)",
    "vehicle.chassis.axle.row1.wheel.right.tire.pressureTarget": "Tire pressure target (front right)",
    "vehicle.chassis.axle.row1.wheel.right.tire.temperature": "Tire temperature (front right)",
    "vehicle.chassis.axle.row2.wheel.left.tire.pressure": "Tire pressure (rear left)",
    "vehicle.chassis.axle.row2.wheel.left.tire.pressureTarget": "Tire pressure target (rear left)",
    "vehicle.chassis.axle.row2.wheel.left.tire.temperature": "Tire temperature (rear left)",
    "vehicle.chassis.axle.row2.wheel.right.tire.pressure": "Tire pressure (rear right)",
    "vehicle.chassis.axle.row2.wheel.right.tire.pressureTarget": "Tire pressure target (rear right)",
    "vehicle.chassis.axle.row2.wheel.right.tire.temperature": "Tire temperature (rear right)",
    "vehicle.chassis.axle.wheel.tire.diagnosis": "Tire diagnostics",
    "vehicle.trip.segment.accumulated.acceleration.starsAverage": "Trip Driving style acceleration",
    "vehicle.trip.segment.accumulated.chassis.brake.starsAverage": "Trip Driving style anticipation",
    "vehicle.trip.segment.accumulated.drivetrain.electricEngine.energyConsumptionComfort": "Trip Energy consumption (comfort mode)",
    "vehicle.trip.segment.accumulated.drivetrain.transmission.setting.fractionDriveEcoPro": "Trip ECO Pro mode share",
    "vehicle.trip.segment.accumulated.drivetrain.transmission.setting.fractionDriveEcoProPlus": "Trip ECO Pro Plus share",
    "vehicle.trip.segment.accumulated.drivetrain.transmission.setting.fractionDriveElectric": "Trip Electric share", 
    "vehicle.trip.segment.end.drivetrain.batteryManagement.hvSoc": "Trip Battery charge level at end of trip",
    "vehicle.trip.segment.end.time": "Trip Last trip time",
    "vehicle.trip.segment.end.travelledDistance": "Trip Last trip distance",
    "vehicle.vehicle.averageWeeklyDistanceLongTerm": "Trip Average distance per week (long-term)",
    "vehicle.vehicle.averageWeeklyDistanceShortTerm": "Trip Average distance per week",
    "vehicle.body.trunk.door.isOpen": "Tailgate door state",
    "vehicle.body.trunk.isLocked": "Tailgate lock",
    "vehicle.body.trunk.isOpen": "Tailgate state",
    "vehicle.body.trunk.left.door.isOpen": "Tailgate door state (left)",
    "vehicle.body.trunk.lower.door.isOpen": "Tailgate door state (lower)",
    "vehicle.body.trunk.right.door.isOpen": "Tailgate door state (right)",
    "vehicle.body.trunk.upper.door.isOpen": "Tailgate door state (upper)",
    "vehicle.body.trunk.window.isOpen": "Tailgate rear window state",
    "vehicle.body.lights.isRunningOn": "Vehicle Lights state",
    "vehicle.drivetrain.engine.isActive": "Vehicle ignition state",
    "vehicle.drivetrain.engine.isIgnitionOn": "Vehicle engine state",
    "vehicle.drivetrain.internalCombustionEngine.engine.ect": "Vehicle Coolant temperature",
    "vehicle.isMoving": "Vehicle Motion state",
    "vehicle.vehicle.avgAuxPower": "Vehicle Auxiliary power",
    "vehicle.vehicle.deepSleepModeActive": "Vehicle deep sleep mode",
    "vehicle.vehicle.travelledDistance": "Vehicle mileage",
    "vehicle.cabin.infotainment.displayUnit.distance": "Vehicle Info Display unit (distance)",
    "vehicle.cabin.infotainment.hmi.distanceUnit": "Vehicle Info Distance unit",
    "vehicle.cabin.infotainment.isMobilePhoneConnected": "Vehicle Info Mobile phone connection state",
    "vehicle.channel.ista.obfcm.lastTransmissionStatus": "Vehicle Info OBFCM last transfer state",
    "vehicle.channel.ngtp.timeVehicle": "Vehicle Info Time in vehicle",
    "vehicle.electronicControlUnit.diagnosticTroubleCodes.raw": "Vehicle Info Fault memory",
    "vehicle.extras.optionalEquipment.code": "Vehicle Info Optional equipment list",
    "vehicle.look.image": "Vehicle Info Image",
    "vehicle.sim.status": "Vehicle Info SIM activation state",
    "vehicle.vehicle.timeSetting": "Vehicle Info Time zone setting",
    "vehicle.vehicleIdentification.basicVehicleData": "Vehicle Info Basic vehicle data",
    "vehicle.cabin.window.row1.driver.status": "Window state (front driver)",
    "vehicle.cabin.window.row1.passenger.status": "Window state (front passenger)",
    "vehicle.cabin.window.row2.driver.status": "Window state (rear driver)",
    "vehicle.cabin.window.row2.passenger.status": "Window state (rear passenger)",
}
