"""Descriptor title overrides generated from BMW catalogue."""

DESCRIPTOR_TITLES = {
    "vehicle.sim.status": "SIM Card Activation",
    "vehicle.vehicleIdentification.basicVehicleData": "Vehicle Basic Data",
    "vehicle.look.image": "Vehicle Image",
    "vehicle.drivetrain.batteryManagement.batterySizeMax": "High Voltage Battery Size",
    "vehicle.extras.optionalEquipment.code": "Special Equipment List",
    "vehicle.drivetrain.electricEngine.hvsMaxEnergyAbsolute": "High Voltage Energy Capacity",
    "vehicle.vehicle.antiTheftAlarmSystem.alarm.activationTime": "Antitheft Alarm Activation Time",
    "vehicle.status.conditionBasedServicesCount": "CBS Reports Count",
    "vehicle.cabin.infotainment.navigation.pointsOfInterests.available": "Free Spaces POI Count",
    "vehicle.cabin.infotainment.displayUnit.distance": "Display Unit Instrument",
    "vehicle.cabin.infotainment.navigation.currentLocation.heading": "Navigation Heading",
    "vehicle.electricalSystem.battery.voltage": "Battery Voltage",
    "vehicle.service.preferredSevicePartner": "Preferred Service Partner",
    "vehicle.isMoving": "Vehicle State Motion",
    "vehicle.status.serviceTime.inspectionDateLegal": "Next Inspection Date",
    "vehicle.channel.ngtp.timeVehicle": "Date Time",
    "vehicle.vehicle.antiTheftAlarmSystem.alarm.isOn": "Anti Theft Alarm Switched",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row3.passengerSide.heating": "Direct Heating Passenger Side Third",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row2.passengerSide.heating": "Direct Heating Rear Passenger Side",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row1.passengerSide.heating": "Passenger Seat Heating Start",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row3.driverSide.heating": "Direct Heating Driver Side Third",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row2.driverSide.heating": "Direct Heating Driver Side Rear",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.steeringWheel.heating": "Steering Wheel Heating Start",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row1.driverSide.heating": "Driver Seat Heating Start",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row3.passengerSide.cooling": "Direct Cooling Passenger Side Third",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row2.passengerSide.cooling": "Direct Cooling Passenger Side Rear",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row1.passengerSide.cooling": "Direct Cooling Passenger Side Front",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row3.driverSide.cooling": "Direct Cooling Driver Side Third",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row2.driverSide.cooling": "Direct Cooling Driver Side Rear",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row1.driverSide.cooling": "Direct Cooling Seat Driver Side",
    "vehicle.cabin.hvac.preconditioning.configuration.isRemoteEngineStartDisclaimer": "Disclaimer Remote Air Conditioning",
    "vehicle.status.serviceDistance.next": "Distance Next Service",
    "vehicle.status.serviceDistance.yellow": "Distance Threshold Service",
    "vehicle.cabin.infotainment.navigation.destinationSet.distance": "Distance Navigation Destination",
    "vehicle.cabin.hvac.preconditioning.status.rearDefrostActive": "Rear Defrost Active",
    "vehicle.body.trunk.window.isOpen": "Unlocking Rear Window",
    "vehicle.vehicle.preConditioning.isRemoteEngineStartAllowed": "Permission Use Engine Preconditioning",
    "vehicle.electronicControlUnit.diagnosticTroubleCodes.raw": "Error Memory",
    "vehicle.cabin.hvac.preconditioning.status.progress": "Progress Pre Conditioning",
    "vehicle.cabin.sunroof.overallStatus": "Overall Status Sunroof",
    "vehicle.electricalSystem.battery.serviceDemand.replace": "Battery Health Status",
    "vehicle.vehicle.preConditioning.error": "Reason Non Execution Preconditioning Air",
    "vehicle.vehicle.travelledDistance": "Mileage",
    "vehicle.cabin.sunroof.tiltStatus": "Tilt Status Sunroof",
    "vehicle.cabin.hvac.preconditioning.status.comfortState": "Comfort State Pre Conditioning",
    "vehicle.cabin.infotainment.isMobilePhoneConnected": "Pairing Mobile Phone",
    "vehicle.drivetrain.internalCombustionEngine.engine.ect": "Coolant Temperature",
    "vehicle.drivetrain.electricEngine.charging.profile.mode": "Charging Profile",
    "vehicle.cabin.steeringWheel.heating": "Steering Wheel Heating",
    "vehicle.body.trunk.left.door.isOpen": "Left Trunk Door Open",
    "vehicle.cabin.infotainment.navigation.pointsOfInterests.max": "Maximum Number Pois Stored Navigation",
    "vehicle.cabin.infotainment.navigation.destinationSet.latitude": "Navigation Destination Geographical Latitude",
    "vehicle.cabin.infotainment.navigation.destinationSet.longitude": "Navigation Destination Geographical Longitude",
    "vehicle.electricalSystem.battery.stateOfCharge": "Low Voltage Battery",
    "vehicle.electricalSystem.battery.stateOfChargePlausibility": "Low Voltage Battery Plausibility",
    "vehicle.electricalSystem.battery.serviceDemand.recharge": "Need Recharge Battery",
    "vehicle.vehicle.preConditioning.isRemoteEngineRunning": "Use Engine Preconditioning",
    "vehicle.body.trunk.upper.door.isOpen": "Upper Trunk Door Opened",
    "vehicle.cabin.infotainment.navigation.currentLocation.latitude": "Navigation Latitude",
    "vehicle.cabin.infotainment.navigation.currentLocation.longitude": "Navigation Longitude",
    "vehicle.cabin.infotainment.navigation.currentLocation.altitude": "Position Above Mean Sea Level",
    "vehicle.cabin.sunroof.shade.position": "Position Parasol",
    "vehicle.body.trunk.right.door.isOpen": "Right Trunk Door Open",
    "vehicle.cabin.sunroof.relativePosition": "Relative Position Sunroof",
    "vehicle.cabin.infotainment.navigation.remainingRange": "Remaining Range",
    "vehicle.cabin.hvac.preconditioning.status.remainingRunningTime": "Remaining Time Pre Conditioning",
    "vehicle.vehicle.antiTheftAlarmSystem.alarm.armStatus": "Arming Status Anti Theft Alarm",
    "vehicle.cabin.seat.row3.passengerSide.heating": "Seat Heating Passenger Side Third",
    "vehicle.cabin.seat.row2.passengerSide.heating": "Seat Heating Rear Passenger Side",
    "vehicle.cabin.seat.row1.passengerSide.heating": "Seat Heating Front Passenger Side",
    "vehicle.cabin.seat.row3.driverSide.heating": "Seat Heating Driver Side Third",
    "vehicle.cabin.seat.row2.driverSide.heating": "Seat Heating Driver Side Rear",
    "vehicle.cabin.seat.row1.driverSide.heating": "Seat Heating Driver Side Front",
    "vehicle.cabin.seat.row3.passengerSide.cooling": "Seat Cooling Passenger Side Third",
    "vehicle.cabin.seat.row2.passengerSide.cooling": "Seat Cooling Rear Passenger Side",
    "vehicle.cabin.seat.row1.passengerSide.cooling": "Seat Cooling Front Passenger Side",
    "vehicle.cabin.seat.row3.driverSide.cooling": "Seat Cooling Driver Side Third",
    "vehicle.cabin.seat.row2.driverSide.cooling": "Seat Cooling Driver Side Rear",
    "vehicle.cabin.seat.row1.driverSide.cooling": "Seat Cooling Driver Side Front",
    "vehicle.chassis.axle.wheel.tire.diagnosis": "Smart Maintenance Tire Diagnostics",
    "vehicle.serviceDemand.defect.id": "Smart Maintenance Live Diagnostics",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.targetTemperature": "Target Temperature Directstart",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.targetTemperature": "Target Temperature",
    "vehicle.cabin.hvac.preconditioning.status.isExteriorMirrorHeatingActive": "Mirror Heating Active",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.steeringWheel.heating": "Standard Steering Wheel Heating",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row3.passengerSide.heating": "Standard Seat Heating Passenger Side",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row2.passengerSide.heating": "Standard Seat Heating Rear Passenger",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row1.passengerSide.heating": "Standard Seat Heating Front Passenger",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row3.driverSide.heating": "Standard Seat Heating Driver Side",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row2.driverSide.heating": "Standard Seat Heating Driver Side",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row1.driverSide.heating": "Standard Seat Heating Driver Side",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row3.passengerSide.cooling": "Standard Seat Cooling Passenger Side",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row2.passengerSide.cooling": "Standard Seat Cooling Passenger Side",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row1.passengerSide.cooling": "Standard Seat Cooling Front Passenger",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row3.driverSide.cooling": "Standard Seat Cooling Driver Side",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row2.driverSide.cooling": "Standard Seat Cooling Driver Side",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row1.driverSide.cooling": "Standard Seat Cooling Driver Side",
    "vehicle.body.trunk.door.isOpen": "Open Trunk Door Status",
    "vehicle.cabin.hvac.statusAirPurification": "HVAC Air Purification Status",
    "vehicle.body.hood.isOpen": "Hood Status",
    "vehicle.cabin.door.row2.driver.isOpen": "Rear Left Door Status",
    "vehicle.cabin.door.row2.passenger.isOpen": "Rear Right Door Status",
    "vehicle.cabin.door.row1.driver.isOpen": "Front Left Door Status",
    "vehicle.cabin.door.row1.passenger.isOpen": "Front Right Door Status",
    "vehicle.cabin.door.lock.status": "Doors Status",
    "vehicle.body.trunk.isLocked": "Trunk Locking Status",
    "vehicle.cabin.convertible.roofStatus": "Convertible Roof Status",
    "vehicle.cabin.convertible.roofRetractableStatus": "Convertible Roof Status",
    "vehicle.cabin.window.row2.driver.status": "Rear Left Window Status",
    "vehicle.cabin.window.row2.passenger.status": "Rear Right Window Status",
    "vehicle.cabin.window.row1.driver.status": "Front Left Window Status",
    "vehicle.cabin.window.row1.passenger.status": "Front Right Window Status",
    "vehicle.body.trunk.isOpen": "Trunk Lid Status",
    "vehicle.cabin.sunroof.status": "Sunroof Status",
    "vehicle.channel.ista.obfcm.lastTransmissionStatus": "Status About Last Transmission OBFCM",
    "vehicle.cabin.door.row2.passenger.position": "Position Rear Passenger Door",
    "vehicle.cabin.door.row1.passenger.position": "Position Front Passenger Door",
    "vehicle.cabin.door.row2.driver.position": "Position Rear Driver Door",
    "vehicle.cabin.door.row1.driver.position": "Position Front Driver Door",
    "vehicle.drivetrain.fuelSystem.level": "Tank Level",
    "vehicle.drivetrain.fuelSystem.remainingFuel": "Tank Capacity",
    "vehicle.vehicle.deepSleepModeActive": "Deep Sleep Mode",
    "vehicle.body.trunk.lower.door.isOpen": "Lower Trunk Door Opened",
    "vehicle.vehicle.preConditioning.remainingTime": "Remaining Duration Preconditioning",
    "vehicle.channel.teleservice.status": "Availability Teleservices",
    "vehicle.vehicle.preConditioning.activity": "Preconditioning Status Air Conditioning",
    "vehicle.cabin.infotainment.navigation.destinationSet.arrivalTime": "Time Navigation Destination",
    "vehicle.status.serviceTime.hUandAuServiceYellow": "Time Threshold Main Exhaust Gas",
    "vehicle.status.serviceTime.yellow": "Time Threshold Service",
    "vehicle.channel.teleservice.lastManualCallTime": "Last Manual Teleservice Call Time",
    "vehicle.channel.teleservice.lastBreakdownCallTime": "Last Teleservice Breakdown Call Time",
    "vehicle.vehicle.timeSetting": "Time Zone Setting",
    "vehicle.body.lights.isRunningOn": "Lights Condition",
    "vehicle.cabin.door.status": "Doors Condition",
    "vehicle.drivetrain.engine.isActive": "Ignition Condition",
    "vehicle.drivetrain.engine.isIgnitionOn": "Engine Status Off",
    "vehicle.status.checkControlMessages": "Check Messages",
    "vehicle.status.conditionBasedServices": "Condition Based Service",
    "vehicle.status.conditionBasedServicesAverageDistancePerDay": "Average Distance Day",
    "vehicle.vehicle.averageWeeklyDistanceShortTerm": "Average Distance Week",
    "vehicle.vehicle.averageWeeklyDistanceLongTerm": "Average Distance Week Long Term",
    "vehicle.drivetrain.fuelSystem.consumptionOverLifeTime.overall.fuel": "Total Fuel Consumption According Legal",
    "vehicle.vehicle.speedRange.upperBound": "Speed Range Above",
    "vehicle.vehicle.speedRange.lowerBound": "Speed Range Below",
    "vehicle.learningNavigation": "Learning Navigation",
    "vehicle.drivetrain.fuelSystem.consumptionOverLifeTime.inChargeIncreasing.fuel": "OBFCM Total Fuel Consumption During",
    "vehicle.drivetrain.fuelSystem.consumptionOverLifeTime.inChargeDepleting.fuel": "OBFCM Total Operating Fuel Consumption",
    "vehicle.drivetrain.fuelSystem.consumptionOverLifeTime.inChargeDepleting.referenceDistanceEngineOn": "OBFCM Reference Distance Electric Operation",
    "vehicle.drivetrain.fuelSystem.consumptionOverLifeTime.inChargeDepleting.referenceDistanceEngineOff": "OBFCM Reference Distance Electric Operation",
    "vehicle.drivetrain.fuelSystem.consumptionOverLifeTime.overall.referenceDistance": "OBFCM Reference Distance Measuring Fuel",
    "vehicle.drivetrain.fuelSystem.consumptionOverLifeTime.inChargeIncreasing.referenceDistance": "OBFCM Reference Route Charging Mode",
    "vehicle.drivetrain.lastRemainingRange": "Last Sent Remaining Range",
    "vehicle.privacySettings.dataCollection.regulations.obfcm": "Consent OBFCM Data Transfer EU",
    "vehicle.channel.teleservice.lastAutomaticServiceCallTime": "Teleservice Call",
    "vehicle.channel.teleservice.lastTeleserviceReportTime": "Teleservice Report",
    "vehicle.powertrain.electric.battery.charging.preferenceSmartCharging": "Smart Charging Option",
    "vehicle.drivetrain.electricEngine.charging.profile.settings.biDirectionalCharging.departureTimeRelevant": "Departure Time Relevant",
    "vehicle.drivetrain.electricEngine.charging.modeDeviation": "Deviation Charging Mode",
    "vehicle.drivetrain.electricEngine.charging.acVoltage": "AC Charging Voltage",
    "vehicle.drivetrain.electricEngine.charging.acAmpere": "AC Charging",
    "vehicle.drivetrain.electricEngine.charging.acRestriction.isChosen": "AC Charging Limitation Selection",
    "vehicle.trip.segment.accumulated.drivetrain.transmission.setting.fractionDriveEcoPro": "ECO Mode Activation Duration Last",
    "vehicle.trip.segment.accumulated.drivetrain.transmission.setting.fractionDriveEcoProPlus": "Activation Duration ECO PLUS Mode",
    "vehicle.drivetrain.electricEngine.charging.level": "Predicted State Charge",
    "vehicle.powertrain.electric.battery.charging.acousticLimit": "Acoustic Limitation Charging Process",
    "vehicle.powertrain.electric.departureTime.displayControl": "Display Departure Time",
    "vehicle.powertrain.electric.chargingDuration.displayControl": "Display Charging Time",
    "vehicle.drivetrain.electricEngine.charging.windowSelection": "Selecting Most Favorable Charging Window",
    "vehicle.powertrain.electric.battery.preconditioning.automaticMode.statusFeedback": "Feedback Status Preconditioning",
    "vehicle.powertrain.tractionBattery.charging.port.anyPosition.isPlugged": "Battery Charging Port Connected Any",
    "vehicle.powertrain.tractionBattery.charging.port.anyPosition.flap.isAutomaticOpenAndCloseActive": "Battery Charging Port Any Position",
    "vehicle.powertrain.tractionBattery.charging.port.anyPosition.flap.isOpen": "Battery Charging Port Any Position",
    "vehicle.powertrain.tractionBattery.charging.port.rearLeft.isPlugged": "Battery Charging Port Connected Rear",
    "vehicle.powertrain.tractionBattery.charging.port.rearLeft.flap.isAutomaticOpenAndCloseActive": "Battery Charging Port Rear Left",
    "vehicle.powertrain.tractionBattery.charging.port.rearLeft.flap.isOpen": "Battery Charging Port Rear Left",
    "vehicle.powertrain.tractionBattery.charging.port.rearMiddle.isPlugged": "Battery Charging Port Connected Rear",
    "vehicle.powertrain.tractionBattery.charging.port.rearMiddle.flap.isAutomaticOpenAndCloseActive": "Battery Charging Port Rear Center",
    "vehicle.powertrain.tractionBattery.charging.port.rearMiddle.flap.isOpen": "Battery Charging Port Rear Center",
    "vehicle.powertrain.tractionBattery.charging.port.rearRight.isPlugged": "Battery Charging Port Connected Rear",
    "vehicle.powertrain.tractionBattery.charging.port.rearRight.flap.isAutomaticOpenAndCloseActive": "Battery Charging Port Rear Right",
    "vehicle.powertrain.tractionBattery.charging.port.rearRight.flap.isOpen": "Battery Charging Port Rear Right",
    "vehicle.powertrain.tractionBattery.charging.port.frontLeft.isPlugged": "Battery Charging Port Connected Front",
    "vehicle.powertrain.tractionBattery.charging.port.frontLeft.flap.isAutomaticOpenAndCloseActive": "Battery Charging Port Front Left",
    "vehicle.powertrain.tractionBattery.charging.port.frontLeft.flap.isOpen": "Battery Charging Port Front Left",
    "vehicle.powertrain.tractionBattery.charging.port.frontMiddle.isPlugged": "Battery Charging Port Connected Front",
    "vehicle.powertrain.tractionBattery.charging.port.frontMiddle.flap.isAutomaticOpenAndCloseActive": "Battery Charging Port Front Center",
    "vehicle.powertrain.tractionBattery.charging.port.frontMiddle.flap.isOpen": "Battery Charging Port Front Center",
    "vehicle.powertrain.tractionBattery.charging.port.frontRight.isPlugged": "Battery Charging Port Connected Front",
    "vehicle.powertrain.tractionBattery.charging.port.frontRight.flap.isAutomaticOpenAndCloseActive": "Battery Charging Port Front Right",
    "vehicle.powertrain.tractionBattery.charging.port.frontRight.flap.isOpen": "Battery Charging Port Front Right",
    "vehicle.powertrain.electric.battery.charging.batteryCarePersisted.isPreservingChargingMode": "Battery Care Charging Mode",
    "vehicle.powertrain.electric.battery.charging.batteryCarePersisted.isActive": "Battery Care Mode Active",
    "vehicle.powertrain.electric.battery.charging.acLimit.selected": "Limiting Charging",
    "vehicle.drivetrain.electricEngine.charging.smeEnergyDeltaFullyCharged": "Energy Required Complete Residual Charge",
    "vehicle.drivetrain.electricEngine.charging.timeToFullyCharged": "Calculated Remaining Charging Time High",
    "vehicle.drivetrain.electricEngine.charging.acRestriction.factor": "Limiting Factor AC Charging",
    "vehicle.powertrain.electric.battery.biDirectionalCharging.availability": "Bidirectional Charging Capability",
    "vehicle.powertrain.electric.battery.charging.dcChargingModeActive": "DC Charging Mode Active",
    "vehicle.drivetrain.avgElectricRangeConsumption": "Average Electrical Consumption",
    "vehicle.vehicle.avgSpeed": "Average Speed",
    "vehicle.trip.segment.accumulated.drivetrain.transmission.setting.fractionDriveElectric": "Electric Portion Last Journey",
    "vehicle.drivetrain.batteryManagement.maxEnergy": "Energy Content High Voltage Battery",
    "vehicle.drivetrain.electricEngine.charging.profile.settings.biDirectionalCharging.dischargeAllowed": "Unloading Allowed",
    "vehicle.drivetrain.electricEngine.charging.lastChargingResult": "Result Last Load",
    "vehicle.trip.segment.accumulated.acceleration.starsAverage": "Driving Style Acceleration",
    "vehicle.trip.segment.accumulated.chassis.brake.starsAverage": "Driving Style Assessment Anticipatory",
    "vehicle.drivetrain.electricEngine.charging.consumptionOverLifeTime.engineOn.gridEnergy": "Total Grid Energy Consumed While",
    "vehicle.drivetrain.electricEngine.charging.consumptionOverLifeTime.engineOff.gridEnergy": "Total Grid Energy Consumed While",
    "vehicle.drivetrain.electricEngine.charging.consumptionOverLifeTime.overall.gridEnergy": "Total Grid Energy Supplied PHEV",
    "vehicle.powertrain.electric.battery.stateOfHealth.displayed": "High Voltage Battery Health Status",
    "vehicle.drivetrain.electricEngine.charging.reasonChargingEnd": "Reason End Store",
    "vehicle.drivetrain.electricEngine.charging.lastChargingReason": "Reason Last Loading",
    "vehicle.body.chargingPort.plugEventId": "ID Charging Port Plug Event",
    "vehicle.electricalSystem.battery48V.stateOfHealth.displayed": "48V Battery Integrity Status",
    "vehicle.powertrain.electric.battery.charging.cableCheckVoltage": "Cable Test Voltage",
    "vehicle.trip.segment.end.traveledDistance": "Mileage Last Trip",
    "vehicle.drivetrain.electricEngine.charging.profile.climatizationActive": "Air Conditioning Active",
    "vehicle.body.chargingPort.combinedStatus": "Charging Port Connection Status",
    "vehicle.drivetrain.electricEngine.charging.chargingMode": "Charging Mode",
    "vehicle.powertrain.electric.battery.charging.history.sessionsList": "Charging History",
    "vehicle.powertrain.electric.battery.charging.power": "Charging Power",
    "vehicle.drivetrain.electricEngine.charging.method": "Charging Method",
    "vehicle.body.chargingPort.isoSessionId": "Loading Session ID",
    "vehicle.drivetrain.electricEngine.charging.status": "Charging Status",
    "vehicle.drivetrain.batteryManagement.header": "High Voltage Battery SOC (SLOW)",
    "vehicle.drivetrain.electricEngine.charging.connectionType": "Charging Method High Voltage Battery",
    "vehicle.drivetrain.electricEngine.charging.phaseNumber": "Charging Process High Voltage Battery",
    "vehicle.trip.segment.end.drivetrain.batteryManagement.hvSoc": "Battery Charge Level",
    "vehicle.powertrain.electric.battery.preconditioning.manualMode.statusFeedback": "Battery Preconditioning Manual",
    "vehicle.powertrain.electric.battery.charging.acLimit.max": "Maximum Charging",
    "vehicle.powertrain.electric.battery.charging.acLimit.min": "Minimum Charging",
    "vehicle.powertrain.electric.battery.stateOfCharge.targetMin": "Minimum Target Charge Level",
    "vehicle.vehicle.avgAuxPower": "Auxiliary Power Consumption Electrical Components",
    "vehicle.drivetrain.electricEngine.charging.consumptionOverLifeTime.overall.referenceDistance": "OBFCM Reference Distance Measuring Supplied",
    "vehicle.drivetrain.electricEngine.charging.profile.preference": "Preference Charging Profile",
    "vehicle.drivetrain.electricEngine.remainingElectricRange": "Forecast Electric Range During Charging",
    "vehicle.drivetrain.totalRemainingRange": "Forecast Total Range During Charging",
    "vehicle.drivetrain.electricEngine.charging.timeRemaining": "Charging Time Remaining",
    "vehicle.drivetrain.electricEngine.charging.profile.isRcpConfigComplete": "RCP Configuration Completed",
    "vehicle.powertrain.electric.battery.charging.batteryCarePersisted.isReducedTargetSoe": "Reduced Target State Energy",
    "vehicle.drivetrain.electricEngine.charging.consumptionOverLifeTime.engineOn.referenceDistance": "Reference Distance Measuring Grid Energy",
    "vehicle.drivetrain.electricEngine.charging.consumptionOverLifeTime.engineOff.referenceDistance": "Reference Distance Measuring Grid Energy",
    "vehicle.drivetrain.electricEngine.charging.routeOptimizedChargingStatus": "Route Optimized Charging Status",
    "vehicle.body.flap.isPermanentlyUnlocked": "Closing State Tailgate",
    "vehicle.powertrain.electric.battery.stateOfCharge.targetSoCForProfessionalMode": "Target Charge Level Professional Mode",
    "vehicle.powertrain.electric.battery.charging.settingsList": "Location Based Charging Settings",
    "vehicle.drivetrain.electricEngine.charging.authentication.status": "Authentication Status Loading",
    "vehicle.powertrain.electric.battery.charging.authenticationStatus": "Authentication Status Loading",
    "vehicle.powertrain.electric.battery.charging.acLimit.isActive": "Charging Limit Status",
    "vehicle.body.chargingPort.status": "Charging Connector Status",
    "vehicle.body.chargingPort.dcStatus": "Charging Connector Status DC Only",
    "vehicle.drivetrain.electricEngine.charging.isSingleImmediateCharging": "Instant Charging Function Status",
    "vehicle.drivetrain.electricEngine.charging.hvStatus": "HV Charging Status",
    "vehicle.drivetrain.electricEngine.charging.connectorStatus": "Charging Plug Status",
    "vehicle.body.chargingPort.statusClearText": "Charging Port Status Text",
    "vehicle.drivetrain.electricEngine.charging.isImmediateChargingSystemReason": "Reason Instant Charging",
    "vehicle.drivetrain.electricEngine.charging.profile.timerType": "Type Charging Timer",
    "vehicle.drivetrain.electricEngine.charging.hvpmFinishReason": "Reason Termination Charging Process",
    "vehicle.powertrain.electric.range.target": "Remaining Electric Range Depending Target",
    "vehicle.drivetrain.electricEngine.kombiRemainingElectricRange": "Remaining Electric Range Km",
    "vehicle.trip.segment.accumulated.drivetrain.electricEngine.energyConsumptionComfort": "Consumption Electrical Energy COMFORT Mode",
    "vehicle.body.chargingPort.lockedStatus": "Charging Port Lock",
    "vehicle.body.chargingPort.isHospitalityActive": "Locking State Charging Plug After",
    "vehicle.trip.segment.end.time": "Last Trip Time",
    "vehicle.powertrain.electric.battery.stateOfCharge.target": "Target State Of Charge",
    "vehicle.trip.segment.accumulated.drivetrain.electricEngine.recuperationTotal": "Energy Recovered Last Trip Amount",
    "vehicle.body.flap.isLocked": "Tailgate Condition",
    "vehicle.powertrain.electric.battery.preconditioning.state": "Preconditioning State",
    "vehicle.cabin.climate.timers.overwriteTimer.action": "Action Overwriting Climate",
    "vehicle.cabin.climate.timers.weekdaysTimer1.action": "Action Timer 1 Weekdays",
    "vehicle.cabin.climate.timers.weekdaysTimer2.action": "Action Timer 2 Weekdays",
    "vehicle.cabin.infotainment.navigation.currentLocation.numberOfSatellites": "Navigation Satellites Count",
    "vehicle.cabin.climate.timers.overwriteTimer.minute": "Minute Overwriting Climate",
    "vehicle.cabin.climate.timers.weekdaysTimer1.minute": "Minute Timer 1 Weekdays",
    "vehicle.cabin.climate.timers.weekdaysTimer2.minute": "Minute Timer 2 Weekdays",
    "vehicle.cabin.infotainment.navigation.currentLocation.fixStatus": "Navigation Fixation Status",
    "vehicle.powertrain.electric.range.displayControl": "Electric Range Display",
    "vehicle.cabin.climate.timers.overwriteTimer.hour": "Hour Overriding Climate",
    "vehicle.cabin.climate.timers.weekdaysTimer1.hour": "Hour Timer 1 Weekdays",
    "vehicle.cabin.climate.timers.weekdaysTimer2.hour": "Hour Timer 2 Weekdays",
    "vehicle.cabin.infotainment.hmi.distanceUnit": "Distance Unit Infotainment",
    "vehicle.chassis.axle.row2.wheel.left.tire.pressure": "Measured Tire Pressure Rear Left",
    "vehicle.chassis.axle.row2.wheel.right.tire.pressure": "Measured Tire Pressure Rear Right",
    "vehicle.chassis.axle.row1.wheel.left.tire.pressure": "Measured Tire Pressure Front Left",
    "vehicle.chassis.axle.row1.wheel.right.tire.pressure": "Measured Tire Pressure Front Right",
    "vehicle.chassis.axle.row2.wheel.left.tire.pressureTarget": "Tire Pressure Rear Left",
    "vehicle.chassis.axle.row2.wheel.right.tire.pressureTarget": "Tire Pressure Rear Right",
    "vehicle.chassis.axle.row1.wheel.left.tire.pressureTarget": "Tire Pressure Front Left",
    "vehicle.chassis.axle.row1.wheel.right.tire.pressureTarget": "Tire Pressure Front Right",
    "vehicle.chassis.axle.row2.wheel.left.tire.temperature": "Tire Temperature Celsius Rear Left",
    "vehicle.chassis.axle.row2.wheel.right.tire.temperature": "Tire Temperature Celsius Rear Right",
    "vehicle.chassis.axle.row1.wheel.left.tire.temperature": "Tire Temperature Celsius Front Left",
    "vehicle.chassis.axle.row1.wheel.right.tire.temperature": "Tire Temperature Celsius Front Right",
    "vehicle.vehicleIdentification.connectedDriveContractList": "Active Connecteddrive Contracts",
}
