"""Descriptor title overrides generated from BMW catalogue."""

DESCRIPTOR_TITLES = {
    "vehicle.sim.status": "Activation status of the built-in SIM card",
    "vehicle.vehicleIdentification.basicVehicleData": "Vehicle basic data",
    "vehicle.look.image": "Vehicle image",
    "vehicle.drivetrain.batteryManagement.batterySizeMax": "Size of the high-voltage battery",
    "vehicle.extras.optionalEquipment.code": "List of special equipment",
    "vehicle.drivetrain.electricEngine.hvsMaxEnergyAbsolute": "Maximum energy content of the high-voltage battery",
    "vehicle.vehicle.antiTheftAlarmSystem.alarm.activationTime": "Activation time of the anti-theft alarm system",
    "vehicle.status.conditionBasedServicesCount": "Number of CBS reports",
    "vehicle.cabin.infotainment.navigation.pointsOfInterests.available": "Number of free spaces POI in the navigation system",
    "vehicle.cabin.infotainment.displayUnit.distance": "Display unit of the instrument display in the vehicle",
    "vehicle.cabin.infotainment.navigation.currentLocation.heading": "Alignment of the vehicle",
    "vehicle.electricalSystem.battery.voltage": "Battery voltage",
    "vehicle.service.preferredSevicePartner": "Preferred Service Partner",
    "vehicle.isMoving": "Vehicle's state of motion",
    "vehicle.status.serviceTime.inspectionDateLegal": "Date of next inspection",
    "vehicle.channel.ngtp.timeVehicle": "Date and time in the vehicle",
    "vehicle.vehicle.antiTheftAlarmSystem.alarm.isOn": "Anti-theft alarm system is switched on",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row3.passengerSide.heating": "Direct heating passenger side third row of seats",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row2.passengerSide.heating": "Direct heating rear passenger side",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row1.passengerSide.heating": "Direct heating front passenger side",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row3.driverSide.heating": "Direct heating driver's side third row of seats",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row2.driverSide.heating": "Direct heating driver's side rear",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.steeringWheel.heating": "Direct heating steering wheel",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row1.driverSide.heating": "Direct heating seat driver's side front",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row3.passengerSide.cooling": "Direct cooling passenger side third row of seats",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row2.passengerSide.cooling": "Direct cooling passenger side rear",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row1.passengerSide.cooling": "Direct cooling passenger side front",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row3.driverSide.cooling": "Direct cooling driver's side third row of seats",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row2.driverSide.cooling": "Direct cooling driver's side rear",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.seat.row1.driverSide.cooling": "Direct cooling seat driver's side front",
    "vehicle.cabin.hvac.preconditioning.configuration.isRemoteEngineStartDisclaimer": "Disclaimer for remote air conditioning",
    "vehicle.status.serviceDistance.next": "Distance to the next service",
    "vehicle.status.serviceDistance.yellow": "Distance threshold for service information",
    "vehicle.cabin.infotainment.navigation.destinationSet.distance": "Distance to navigation destination",
    "vehicle.cabin.hvac.preconditioning.status.rearDefrostActive": "Rear defrosting active",
    "vehicle.body.trunk.window.isOpen": "Unlocking the rear window",
    "vehicle.vehicle.preConditioning.isRemoteEngineStartAllowed": "Permission to use the engine for preconditioning.",
    "vehicle.electronicControlUnit.diagnosticTroubleCodes.raw": "Error memory",
    "vehicle.cabin.hvac.preconditioning.status.progress": "Progress of pre-conditioning",
    "vehicle.cabin.sunroof.overallStatus": "Overall status of the sunroof",
    "vehicle.electricalSystem.battery.serviceDemand.replace": "Battery health status",
    "vehicle.vehicle.preConditioning.error": "Reason for non-execution of preconditioning of stationary air conditioning",
    "vehicle.vehicle.travelledDistance": "Mileage",
    "vehicle.cabin.sunroof.tiltStatus": "Tilt status of the sunroof",
    "vehicle.cabin.hvac.preconditioning.status.comfortState": "Comfort state of pre-conditioning",
    "vehicle.cabin.infotainment.isMobilePhoneConnected": "Pairing mobile phone",
    "vehicle.drivetrain.internalCombustionEngine.engine.ect": "Coolant temperature",
    "vehicle.drivetrain.electricEngine.charging.profile.mode": "Charging profile",
    "vehicle.cabin.steeringWheel.heating": "Steering wheel heating",
    "vehicle.body.trunk.left.door.isOpen": "Left trunk door open",
    "vehicle.cabin.infotainment.navigation.pointsOfInterests.max": "Maximum number of POIs stored in the navigation device",
    "vehicle.cabin.infotainment.navigation.destinationSet.latitude": "Navigation destination – geographical latitude",
    "vehicle.cabin.infotainment.navigation.destinationSet.longitude": "Navigation destination – geographical longitude",
    "vehicle.electricalSystem.battery.stateOfCharge": "Low-voltage battery",
    "vehicle.electricalSystem.battery.stateOfChargePlausibility": "Low-voltage battery plausibility",
    "vehicle.electricalSystem.battery.serviceDemand.recharge": "Need to recharge the battery",
    "vehicle.vehicle.preConditioning.isRemoteEngineRunning": "Use of the engine for preconditioning",
    "vehicle.body.trunk.upper.door.isOpen": "Upper trunk door opened",
    "vehicle.cabin.infotainment.navigation.currentLocation.latitude": "Vehicle position – geographical latitude",
    "vehicle.cabin.infotainment.navigation.currentLocation.longitude": "Vehicle position – longitude",
    "vehicle.cabin.infotainment.navigation.currentLocation.altitude": "Position of the vehicle above mean sea level",
    "vehicle.cabin.sunroof.shade.position": "Position of the parasol",
    "vehicle.body.trunk.right.door.isOpen": "Right trunk door open",
    "vehicle.cabin.sunroof.relativePosition": "Relative position of the sunroof",
    "vehicle.cabin.infotainment.navigation.remainingRange": "Remaining range",
    "vehicle.cabin.hvac.preconditioning.status.remainingRunningTime": "Remaining time of pre-conditioning",
    "vehicle.vehicle.antiTheftAlarmSystem.alarm.armStatus": "Arming status of the anti-theft alarm system",
    "vehicle.cabin.seat.row3.passengerSide.heating": "Seat heating passenger side third row",
    "vehicle.cabin.seat.row2.passengerSide.heating": "Seat heating rear passenger side",
    "vehicle.cabin.seat.row1.passengerSide.heating": "Seat heating front passenger side",
    "vehicle.cabin.seat.row3.driverSide.heating": "Seat heating driver's side third row",
    "vehicle.cabin.seat.row2.driverSide.heating": "Seat heating driver's side rear",
    "vehicle.cabin.seat.row1.driverSide.heating": "Seat heating driver's side front",
    "vehicle.cabin.seat.row3.passengerSide.cooling": "Seat cooling passenger side third row",
    "vehicle.cabin.seat.row2.passengerSide.cooling": "Seat cooling rear passenger side",
    "vehicle.cabin.seat.row1.passengerSide.cooling": "Seat cooling front passenger side",
    "vehicle.cabin.seat.row3.driverSide.cooling": "Seat cooling driver's side third row",
    "vehicle.cabin.seat.row2.driverSide.cooling": "Seat cooling driver's side rear",
    "vehicle.cabin.seat.row1.driverSide.cooling": "Seat cooling driver's side front",
    "vehicle.chassis.axle.wheel.tire.diagnosis": "Smart Maintenance: Digital Tire Diagnostics",
    "vehicle.serviceDemand.defect.id": "Smart Maintenance: Live diagnostics",
    "vehicle.cabin.hvac.preconditioning.configuration.directStartSettings.targetTemperature": "Target temperature for DirectStart",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.targetTemperature": "Target temperature",
    "vehicle.cabin.hvac.preconditioning.status.isExteriorMirrorHeatingActive": "Mirror heating active",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.steeringWheel.heating": "Standard for steering wheel heating",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row3.passengerSide.heating": "Standard for seat heating passenger side third row",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row2.passengerSide.heating": "Standard for seat heating on the rear passenger side",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row1.passengerSide.heating": "Standard for seat heating on the front passenger side",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row3.driverSide.heating": "Standard for seat heating driver's side third row",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row2.driverSide.heating": "Standard for seat heating driver's side rear",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row1.driverSide.heating": "Standard for seat heating driver's side front",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row3.passengerSide.cooling": "Standard for seat cooling passenger side third row",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row2.passengerSide.cooling": "Standard for seat cooling passenger side rear",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row1.passengerSide.cooling": "Standard for seat cooling on the front passenger side",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row3.driverSide.cooling": "Standard for seat cooling driver side third row",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row2.driverSide.cooling": "Standard for seat cooling driver's side rear",
    "vehicle.cabin.hvac.preconditioning.configuration.defaultSettings.seat.row1.driverSide.cooling": "Standard for seat cooling driver's side front",
    "vehicle.body.trunk.door.isOpen": "Status of the open trunk door",
    "vehicle.cabin.hvac.statusAirPurification": "HVAC air purification status",
    "vehicle.body.hood.isOpen": "Hood status",
    "vehicle.cabin.door.row2.driver.isOpen": "Status of the rear left door",
    "vehicle.cabin.door.row2.passenger.isOpen": "Status of the rear right door",
    "vehicle.cabin.door.row1.driver.isOpen": "Status of the front left door",
    "vehicle.cabin.door.row1.passenger.isOpen": "Status of the front right door",
    "vehicle.cabin.door.lock.status": "Status of the doors",
    "vehicle.body.trunk.isLocked": "Trunk locking status",
    "vehicle.cabin.convertible.roofStatus": "Status of the convertible roof",
    "vehicle.cabin.convertible.roofRetractableStatus": "Status of the convertible roof",
    "vehicle.cabin.window.row2.driver.status": "Rear left window status",
    "vehicle.cabin.window.row2.passenger.status": "Rear right window status",
    "vehicle.cabin.window.row1.driver.status": "Front left window status",
    "vehicle.cabin.window.row1.passenger.status": "Status of the front right window",
    "vehicle.body.trunk.isOpen": "Status of the trunk lid",
    "vehicle.cabin.sunroof.status": "Sunroof status",
    "vehicle.channel.ista.obfcm.lastTransmissionStatus": "Status information about the last transmission of OBFCM* values",
    "vehicle.cabin.door.row2.passenger.position": "Position of the rear passenger door",
    "vehicle.cabin.door.row1.passenger.position": "Position of the front passenger door",
    "vehicle.cabin.door.row2.driver.position": "Position of the rear driver's door",
    "vehicle.cabin.door.row1.driver.position": "Position of the front driver's door",
    "vehicle.drivetrain.fuelSystem.level": "Tank level in %",
    "vehicle.drivetrain.fuelSystem.remainingFuel": "Tank capacity",
    "vehicle.vehicle.deepSleepModeActive": "Deep Sleep Mode",
    "vehicle.body.trunk.lower.door.isOpen": "Lower trunk door opened",
    "vehicle.vehicle.preConditioning.remainingTime": "Remaining duration of preconditioning",
    "vehicle.channel.teleservice.status": "Availability of teleservices",
    "vehicle.vehicle.preConditioning.activity": "Preconditioning status of the stationary air conditioning",
    "vehicle.cabin.infotainment.navigation.destinationSet.arrivalTime": "Time to navigation destination",
    "vehicle.status.serviceTime.hUandAuServiceYellow": "Time threshold for main and exhaust gas inspection",
    "vehicle.status.serviceTime.yellow": "Time threshold for service information",
    "vehicle.channel.teleservice.lastManualCallTime": "Time of the last manual teleservice call",
    "vehicle.channel.teleservice.lastBreakdownCallTime": "Time of the last Teleservice Breakdown Call",
    "vehicle.vehicle.timeSetting": "Time zone setting in the vehicle",
    "vehicle.body.lights.isRunningOn": "Condition of the lights",
    "vehicle.cabin.door.status": "Condition of the doors",
    "vehicle.drivetrain.engine.isActive": "Ignition condition",
    "vehicle.drivetrain.engine.isIgnitionOn": "Engine status (on/off)",
    "vehicle.status.checkControlMessages": "Check Control Messages",
    "vehicle.status.conditionBasedServices": "Condition-Based Service",
    "vehicle.status.conditionBasedServicesAverageDistancePerDay": "Average distance per day",
    "vehicle.vehicle.averageWeeklyDistanceShortTerm": "Average distance per week",
    "vehicle.vehicle.averageWeeklyDistanceLongTerm": "Average distance per week (long-term)",
    "vehicle.drivetrain.fuelSystem.consumptionOverLifeTime.overall.fuel": "Total fuel consumption according to legal OBFCM* requirements",
    "vehicle.vehicle.speedRange.upperBound": "Speed range above",
    "vehicle.vehicle.speedRange.lowerBound": "Speed range below",
    "vehicle.learningNavigation": "Learning navigation",
    "vehicle.drivetrain.fuelSystem.consumptionOverLifeTime.inChargeIncreasing.fuel": "OBFCM* total fuel consumption during charging (PHEV only)",
    "vehicle.drivetrain.fuelSystem.consumptionOverLifeTime.inChargeDepleting.fuel": "OBFCM* total operating fuel consumption with battery discharge (PHEV only)",
    "vehicle.drivetrain.fuelSystem.consumptionOverLifeTime.inChargeDepleting.referenceDistanceEngineOn": "OBFCM* reference distance for electric operation and active combustion engine (PHEV only)",
    "vehicle.drivetrain.fuelSystem.consumptionOverLifeTime.inChargeDepleting.referenceDistanceEngineOff": "OBFCM* reference distance for electric operation and inactive combustion engine (PHEV only)",
    "vehicle.drivetrain.fuelSystem.consumptionOverLifeTime.overall.referenceDistance": "OBFCM* reference distance for measuring fuel consumption",
    "vehicle.drivetrain.fuelSystem.consumptionOverLifeTime.inChargeIncreasing.referenceDistance": "OBFCM* reference route in charging mode",
    "vehicle.drivetrain.lastRemainingRange": "Last sent remaining range",
    "vehicle.privacySettings.dataCollection.regulations.obfcm": "Consent to OBFCM* data transfer to the EU",
    "vehicle.channel.teleservice.lastAutomaticServiceCallTime": "Automatic Teleservice Call",
    "vehicle.channel.teleservice.lastTeleserviceReportTime": "Teleservice Report",
    "vehicle.powertrain.electric.battery.charging.preferenceSmartCharging": "\"Smart Charging\" charging option",
    "vehicle.drivetrain.electricEngine.charging.profile.settings.biDirectionalCharging.departureTimeRelevant": "Departure time relevant",
    "vehicle.drivetrain.electricEngine.charging.modeDeviation": "Deviation from charging mode",
    "vehicle.drivetrain.electricEngine.charging.acVoltage": "AC charging voltage",
    "vehicle.drivetrain.electricEngine.charging.acAmpere": "AC charging current",
    "vehicle.drivetrain.electricEngine.charging.acRestriction.isChosen": "AC charging current limitation and selection",
    "vehicle.trip.segment.accumulated.drivetrain.transmission.setting.fractionDriveEcoPro": "ECO mode activation duration of the last trip",
    "vehicle.trip.segment.accumulated.drivetrain.transmission.setting.fractionDriveEcoProPlus": "Activation duration of ECO PLUS mode of the last trip",
    "vehicle.drivetrain.electricEngine.charging.level": "Current predicted state of charge",
    "vehicle.powertrain.electric.battery.charging.acousticLimit": "Acoustic limitation of the charging process",
    "vehicle.powertrain.electric.departureTime.displayControl": "Display of departure time",
    "vehicle.powertrain.electric.chargingDuration.displayControl": "Display of charging time",
    "vehicle.drivetrain.electricEngine.charging.windowSelection": "Selecting the most favorable charging window (Charging Window Selection)",
    "vehicle.powertrain.electric.battery.preconditioning.automaticMode.statusFeedback": "Automatic feedback on the status of preconditioning",
    "vehicle.powertrain.tractionBattery.charging.port.anyPosition.isPlugged": "Battery charging port connected at any position",
    "vehicle.powertrain.tractionBattery.charging.port.anyPosition.flap.isAutomaticOpenAndCloseActive": "Battery charging port at any position, flap opens/closes automatically",
    "vehicle.powertrain.tractionBattery.charging.port.anyPosition.flap.isOpen": "Battery charging port at any position, flap open",
    "vehicle.powertrain.tractionBattery.charging.port.rearLeft.isPlugged": "Battery charging port connected rear left",
    "vehicle.powertrain.tractionBattery.charging.port.rearLeft.flap.isAutomaticOpenAndCloseActive": "Battery charging port rear left, flap opens/closes automatically",
    "vehicle.powertrain.tractionBattery.charging.port.rearLeft.flap.isOpen": "Battery charging port rear left, flap open",
    "vehicle.powertrain.tractionBattery.charging.port.rearMiddle.isPlugged": "Battery charging port connected rear center",
    "vehicle.powertrain.tractionBattery.charging.port.rearMiddle.flap.isAutomaticOpenAndCloseActive": "Battery charging port rear center, flap opens/closes automatically",
    "vehicle.powertrain.tractionBattery.charging.port.rearMiddle.flap.isOpen": "Battery charging port rear center, flap open",
    "vehicle.powertrain.tractionBattery.charging.port.rearRight.isPlugged": "Battery charging port connected at the rear right",
    "vehicle.powertrain.tractionBattery.charging.port.rearRight.flap.isAutomaticOpenAndCloseActive": "Battery charging port rear right, flap opens/closes automatically",
    "vehicle.powertrain.tractionBattery.charging.port.rearRight.flap.isOpen": "Battery charging port rear right, flap open",
    "vehicle.powertrain.tractionBattery.charging.port.frontLeft.isPlugged": "Battery charging port connected front left",
    "vehicle.powertrain.tractionBattery.charging.port.frontLeft.flap.isAutomaticOpenAndCloseActive": "Battery charging port front left, flap opens/closes automatically",
    "vehicle.powertrain.tractionBattery.charging.port.frontLeft.flap.isOpen": "Battery charging port front left, flap open",
    "vehicle.powertrain.tractionBattery.charging.port.frontMiddle.isPlugged": "Battery charging port connected front center",
    "vehicle.powertrain.tractionBattery.charging.port.frontMiddle.flap.isAutomaticOpenAndCloseActive": "Battery charging port front center, flap opens/closes automatically",
    "vehicle.powertrain.tractionBattery.charging.port.frontMiddle.flap.isOpen": "Battery charging port front center, flap open",
    "vehicle.powertrain.tractionBattery.charging.port.frontRight.isPlugged": "Battery charging port connected at the front right",
    "vehicle.powertrain.tractionBattery.charging.port.frontRight.flap.isAutomaticOpenAndCloseActive": "Battery charging port front right, flap opens/closes automatically",
    "vehicle.powertrain.tractionBattery.charging.port.frontRight.flap.isOpen": "Battery charging port front right, flap open",
    "vehicle.powertrain.electric.battery.charging.batteryCarePersisted.isPreservingChargingMode": "Battery Care charging mode",
    "vehicle.powertrain.electric.battery.charging.batteryCarePersisted.isActive": "Battery Care mode active",
    "vehicle.powertrain.electric.battery.charging.acLimit.selected": "Limiting the charging current",
    "vehicle.drivetrain.electricEngine.charging.smeEnergyDeltaFullyCharged": "Energy required for the complete residual charge of the high-voltage battery",
    "vehicle.drivetrain.electricEngine.charging.timeToFullyCharged": "Calculated remaining charging time of the high-voltage battery",
    "vehicle.drivetrain.electricEngine.charging.acRestriction.factor": "Limiting factor for AC charging",
    "vehicle.powertrain.electric.battery.biDirectionalCharging.availability": "Bidirectional charging capability",
    "vehicle.powertrain.electric.battery.charging.dcChargingModeActive": "DC charging mode active",
    "vehicle.drivetrain.avgElectricRangeConsumption": "Average electrical consumption",
    "vehicle.vehicle.avgSpeed": "Average speed",
    "vehicle.trip.segment.accumulated.drivetrain.transmission.setting.fractionDriveElectric": "Electric portion of the last journey",
    "vehicle.drivetrain.batteryManagement.maxEnergy": "Energy content of the high-voltage battery",
    "vehicle.drivetrain.electricEngine.charging.profile.settings.biDirectionalCharging.dischargeAllowed": "Unloading allowed",
    "vehicle.drivetrain.electricEngine.charging.lastChargingResult": "Result of last load",
    "vehicle.trip.segment.accumulated.acceleration.starsAverage": "Driving style assessment 'acceleration behavior'",
    "vehicle.trip.segment.accumulated.chassis.brake.starsAverage": "Driving style assessment 'Anticipatory driving'",
    "vehicle.drivetrain.electricEngine.charging.consumptionOverLifeTime.engineOn.gridEnergy": "Total grid energy consumed while the combustion engine was active",
    "vehicle.drivetrain.electricEngine.charging.consumptionOverLifeTime.engineOff.gridEnergy": "Total grid energy consumed while the combustion engine was not active",
    "vehicle.drivetrain.electricEngine.charging.consumptionOverLifeTime.overall.gridEnergy": "Total grid energy supplied to the vehicle (PHEV only)",
    "vehicle.powertrain.electric.battery.stateOfHealth.displayed": "High-voltage battery health status (SOCE)",
    "vehicle.drivetrain.electricEngine.charging.reasonChargingEnd": "Reason for the end of the store",
    "vehicle.drivetrain.electricEngine.charging.lastChargingReason": "Reason last loading",
    "vehicle.body.chargingPort.plugEventId": "ID of the charging port plug-in event",
    "vehicle.electricalSystem.battery48V.stateOfHealth.displayed": "48V battery integrity status",
    "vehicle.powertrain.electric.battery.charging.cableCheckVoltage": "Cable test voltage",
    "vehicle.trip.segment.end.traveledDistance": "Mileage of the last trip",
    "vehicle.drivetrain.electricEngine.charging.profile.climatizationActive": "Air conditioning active",
    "vehicle.body.chargingPort.combinedStatus": "Charging port connection status",
    "vehicle.drivetrain.electricEngine.charging.chargingMode": "Charging mode",
    "vehicle.powertrain.electric.battery.charging.history.sessionsList": "Charging history",
    "vehicle.powertrain.electric.battery.charging.power": "Charging power",
    "vehicle.drivetrain.electricEngine.charging.method": "Charging method and plug type",
    "vehicle.body.chargingPort.isoSessionId": "Loading session ID",
    "vehicle.drivetrain.electricEngine.charging.status": "Charging status",
    "vehicle.drivetrain.batteryManagement.header": "Charging status of the high-voltage battery",
    "vehicle.drivetrain.electricEngine.charging.connectionType": "Charging method of the high-voltage battery (inductive/conductive)",
    "vehicle.drivetrain.electricEngine.charging.phaseNumber": "Charging process of the high-voltage battery (phases)",
    "vehicle.trip.segment.end.drivetrain.batteryManagement.hvSoc": "Battery charge level",
    "vehicle.powertrain.electric.battery.preconditioning.manualMode.statusFeedback": "Manual feedback on the status of preconditioning",
    "vehicle.powertrain.electric.battery.charging.acLimit.max": "Maximum charging current",
    "vehicle.powertrain.electric.battery.charging.acLimit.min": "Minimum charging current",
    "vehicle.powertrain.electric.battery.stateOfCharge.targetMin": "Minimum target charge level",
    "vehicle.vehicle.avgAuxPower": "Auxiliary power (power consumption of electrical components)",
    "vehicle.drivetrain.electricEngine.charging.consumptionOverLifeTime.overall.referenceDistance": "OBFCM* reference distance for measuring the supplied grid energy",
    "vehicle.drivetrain.electricEngine.charging.profile.preference": "Preference for the charging profile",
    "vehicle.drivetrain.electricEngine.remainingElectricRange": "Forecast of electric range during charging",
    "vehicle.drivetrain.totalRemainingRange": "Forecast of the total range during the charging process",
    "vehicle.drivetrain.electricEngine.charging.timeRemaining": "Forecast of remaining loading time",
    "vehicle.drivetrain.electricEngine.charging.profile.isRcpConfigComplete": "RCP configuration completed",
    "vehicle.powertrain.electric.battery.charging.batteryCarePersisted.isReducedTargetSoe": "Reduced target for the State of Energy",
    "vehicle.drivetrain.electricEngine.charging.consumptionOverLifeTime.engineOn.referenceDistance": "Reference distance for measuring the grid energy supplied while the combustion engine was active",
    "vehicle.drivetrain.electricEngine.charging.consumptionOverLifeTime.engineOff.referenceDistance": "Reference distance for measuring the grid energy supplied while the combustion engine was not active",
    "vehicle.drivetrain.electricEngine.charging.routeOptimizedChargingStatus": "Route-optimized charging status",
    "vehicle.body.flap.isPermanentlyUnlocked": "Closing state of the tailgate",
    "vehicle.powertrain.electric.battery.stateOfCharge.targetSoCForProfessionalMode": "Target charge level for professional mode",
    "vehicle.powertrain.electric.battery.charging.settingsList": "Location-based charging settings",
    "vehicle.drivetrain.electricEngine.charging.authentication.status": "Authentication status for loading",
    "vehicle.powertrain.electric.battery.charging.authenticationStatus": "Authentication status for loading",
    "vehicle.powertrain.electric.battery.charging.acLimit.isActive": "Status of the charging limit",
    "vehicle.body.chargingPort.status": "Status of the charging connector",
    "vehicle.body.chargingPort.dcStatus": "Charging connector status (DC only)",
    "vehicle.drivetrain.electricEngine.charging.isSingleImmediateCharging": "Status of the instant charging function",
    "vehicle.drivetrain.electricEngine.charging.hvStatus": "Status of the HV charging system",
    "vehicle.drivetrain.electricEngine.charging.connectorStatus": "Charging plug status",
    "vehicle.body.chargingPort.statusClearText": "Charging port status text",
    "vehicle.drivetrain.electricEngine.charging.isImmediateChargingSystemReason": "System reason for instant charging",
    "vehicle.drivetrain.electricEngine.charging.profile.timerType": "Type of charging timer",
    "vehicle.drivetrain.electricEngine.charging.hvpmFinishReason": "Reason for termination of a charging process",
    "vehicle.powertrain.electric.range.target": "Remaining electric range depending on the target state of charge",
    "vehicle.drivetrain.electricEngine.kombiRemainingElectricRange": "Remaining electric range in km",
    "vehicle.trip.segment.accumulated.drivetrain.electricEngine.energyConsumptionComfort": "Consumption of electrical energy in COMFORT mode of the last trip",
    "vehicle.body.chargingPort.lockedStatus": "Locking state of the charging port",
    "vehicle.body.chargingPort.isHospitalityActive": "Locking state of the charging plug after full charging",
    "vehicle.trip.segment.end.time": "Time of last trip",
    "vehicle.powertrain.electric.battery.stateOfCharge.target": "Target value of the high-voltage battery state of charge",
    "vehicle.trip.segment.accumulated.drivetrain.electricEngine.recuperationTotal": "Amount of energy recovered from the last trip",
    "vehicle.body.flap.isLocked": "Condition of the tailgate",
    "vehicle.powertrain.electric.battery.preconditioning.state": "State of preconditioning",
    "vehicle.cabin.climate.timers.overwriteTimer.action": "Action for overwriting the automatic climate control",
    "vehicle.cabin.climate.timers.weekdaysTimer1.action": "Action for timer 1 on weekdays",
    "vehicle.cabin.climate.timers.weekdaysTimer2.action": "Action for timer 2 on weekdays",
    "vehicle.cabin.infotainment.navigation.currentLocation.numberOfSatellites": "Number of navigation satellites",
    "vehicle.cabin.climate.timers.overwriteTimer.minute": "Minute for overwriting the automatic climate control",
    "vehicle.cabin.climate.timers.weekdaysTimer1.minute": "Minute for automatic timer 1 on weekdays",
    "vehicle.cabin.climate.timers.weekdaysTimer2.minute": "Minute for automatic timer 2 on weekdays",
    "vehicle.cabin.infotainment.navigation.currentLocation.fixStatus": "Navigation fixation status",
    "vehicle.powertrain.electric.range.displayControl": "Control of the electric range display",
    "vehicle.cabin.climate.timers.overwriteTimer.hour": "Hour for overriding the automatic climate control",
    "vehicle.cabin.climate.timers.weekdaysTimer1.hour": "Hour for automatic timer 1 on weekdays",
    "vehicle.cabin.climate.timers.weekdaysTimer2.hour": "Hour for automatic timer 2 on weekdays",
    "vehicle.cabin.infotainment.hmi.distanceUnit": "Distance unit in infotainment",
    "vehicle.chassis.axle.row2.wheel.left.tire.pressure": "Measured tire pressure rear left",
    "vehicle.chassis.axle.row2.wheel.right.tire.pressure": "Measured tire pressure rear right",
    "vehicle.chassis.axle.row1.wheel.left.tire.pressure": "Measured tire pressure front left",
    "vehicle.chassis.axle.row1.wheel.right.tire.pressure": "Measured tire pressure front right",
    "vehicle.chassis.axle.row2.wheel.left.tire.pressureTarget": "Tire pressure rear left",
    "vehicle.chassis.axle.row2.wheel.right.tire.pressureTarget": "Tire pressure rear right",
    "vehicle.chassis.axle.row1.wheel.left.tire.pressureTarget": "Tire pressure front left",
    "vehicle.chassis.axle.row1.wheel.right.tire.pressureTarget": "Tire pressure front right",
    "vehicle.chassis.axle.row2.wheel.left.tire.temperature": "Tire temperature in Celsius, rear left",
    "vehicle.chassis.axle.row2.wheel.right.tire.temperature": "Tire temperature in Celsius, rear right",
    "vehicle.chassis.axle.row1.wheel.left.tire.temperature": "Tire temperature in Celsius, front left",
    "vehicle.chassis.axle.row1.wheel.right.tire.temperature": "Tire temperature in Celsius, front right",
    "vehicle.vehicleIdentification.connectedDriveContractList": "Active ConnectedDrive contracts",
}
